---
all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
    production:
      hosts:
        ecotrack-prod:
          ansible_host: 10.0.0.4
          ansible_user: azureuser
          ansible_ssh_private_key_file: ~/.ssh/ecotrack_azure.pem
